# coding: utf-8

"""
    Description: python client
    Generated by: ecloud-sdk
"""

from ecloudsdkcore.config.config import Config
from ecloudsdkcscenter.v1.model import *
from ecloudsdkcscenter.v1.client import Client


class OpenAPISample:
    def __init__(self):
        pass

    @staticmethod
    def create_client(
        access_key: str,
        secret_key: str,
        pool_id: str
    ) -> Client:
        """
        使用AK&SK初始化账号Client
        @param access_key:
        @param secret_key:
        @param pool_id:
        @return: Client
        @throws Exception
        """
        config = Config(
            access_key=access_key,
            secret_key=secret_key,
            pool_id=pool_id
        )
        return Client(config)

    @staticmethod
    def get_messages() -> str:
        client = OpenAPISample.create_client("efd1dbbb761847ba89c2508c44281192", "3ec08cb690f34a4cad23cf5b8b3cb3a1", "CIDC-RP-25")
        request = MessageListRequest()
        message_list_query = MessageListQuery()
        message_list_query.size = 2
        message_list_query.page = 0
        request.message_list_query = message_list_query
        result = client.message_list(request)
        return result
    
    @staticmethod
    def get_leaks() -> str:
        client = OpenAPISample.create_client("efd1dbbb761847ba89c2508c44281192", "3ec08cb690f34a4cad23cf5b8b3cb3a1", "CIDC-RP-25")
        
        result = client.get_leak_stats()
        return result

